/gripper_interface_node:
  ros__parameters:
    topics:
      joy: "/joy"           # from joy to this node
      ref: "/gripper_ref"   # from this node to controller -->
      uin: "/gripper_u"     # from controller to this node <--
      pwm: "/gripper_pwm"   # from this node to gripper motor drivers

    pwm:
      gain: 200 # value range: pwm_idle +/- pwm_gain
      idle: 1500

    i2c:
      bus: 1
      address: 0x21
