/gripper_interface_node:
  ros__parameters:
    topics:
      joy: "/joy"
      pwm: "/gripper_pwm"
      joint_state: "/joint_state_gripper"

    pwm:
      gain: 200 # value range: pwm_idle +/- pwm_gain
      idle: 1500

    i2c:
      bus: 7
      address: 0x31
    can:
      is_enabled: 0
      interface: "can0"
      
