/gripper_interface_node:
  ros__parameters:
    topics:
      joy: "/joy"
      pwm: "/gripper_pwm"
      joint_state: "/joint_state_gripper"
    pwm:
      gain: 800 # value range: pwm_idle +/- pwm_gain
      idle: 1500
