gripper_interface_node:
  ros__parameters:
    topics:
      joy: "/joy"
      pwm: "/gripper/pwm"
      joint_state: "/gripper/joint_states"

    pwm:
      gain: 800
      idle: 1500

    serial:
      port: "/dev/ttyUSB0"
      baudrate: 115200
