 /**:
  ros__parameters:
    # Integration loop period in milliseconds
    time_step_ms: 10

    # Filter dynamics parameters
    zeta: [1.0, 1.0]
    omega: [0.4, 0.4]

    # Topics
    topics:
      guidance_gripper: "nautilus/gripper/guidance"
      gripper_state: "nautilus/gripper/state"

    # Action servers
    action_servers:
      gripper_reference_filter: "nautilus/gripper/reference_filter"
