/**:
  ros__parameters:
    # Publish loop period in milliseconds
    time_step_ms: 10

    # Topics
    topics:
      # Output: velocity command to the gripper interface node
      control: "nautilus/gripper/control"

    # Action servers
    action_servers:
      gripper_open_loop_controller: "nautilus/gripper/open_loop_controller"
